[features]
seeds = true
skip-lint = false

[programs.localnet]
teamdao_tournament = "Anm8zfCbBFfZ4sWC3qRX5KKMpFdr7cLHbNGq1EKerACC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
